package:
  name: pangalactic.node
  version: "0.1.dev99"

source:
  path: # [path to source]

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=0.1.dev99
    - autobahn
    - binaryornot
    - future
    - matplotlib
    - openjpeg >=2.3.0
    - pillow <=4.1.1    # 4.2.x is broken
    - pyqt >=5.6,<5.7
    - python {{PY_VER}}
    - pythonocc-core >=0.18.1   # from pythonocc channel
    # -----------------------------------------------------
    # pythonocc pulls in these dependencies from dlr-sc channel:
    # - freeimageplus
    # - gl2ps
    # - jpeg 9b
    # - tbb
    # -----------------------------------------------------
    # pinning ruamel_yaml advised for production-level stability
    - ruamel_yaml <=0.15
    - sqlalchemy
    - twisted
    # twisted pulls in these dependencies:
    # - service_identity
    # - zope
    # - zope.interface
    # -----------------------------------------------------
    # packages locally built and installed from local repo
    - louie
    - qt5reactor

# test:
  # imports:
    # - sometestpackage

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

