package:
  name: pangalactic.node
  version: "2.0"

source:
  path: # [path to source]

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=2.0
    - autobahn >= 20.7.1
    # autobahn pulls in:
    # - txaio
    - binaryornot
    - numpy
    - pynacl
    - pyqt >=5.6
    - pyqtgraph
    - python {{PY_VER}}
    - pythonocc-core >=0.18.2
    # -----------------------------------------------------
    # pythonocc pulls in these dependencies from dlr-sc channel:
    # - freeimageplus
    # - gl2ps
    # - jpeg >=9b
    # - tbb
    # -----------------------------------------------------
    # pinning ruamel_yaml advised for production-level stability
    - ruamel_yaml <=0.15
    - sqlalchemy
    - twisted
    # twisted pulls in these dependencies:
    # - service_identity
    # - zope
    # - zope.interface
    # -----------------------------------------------------
    # packages locally built and installed from local repo
    - louie
    - qt5reactor

# test:
  # imports:
    # - sometestpackage

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

