package:
  name: pangalaxian
  version: "4.0.dev5"

source:
  # path to source ... modify if necessary
  path: # C:\Users\swaterbu\clones\pangalactic.node

build:
  number: 1
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=4.0.dev5
    - autobahn
    - binaryornot
    - packaging
    - pynacl
    - pyqt
    - python {{PY_VER}}
    - pythonocc-core ==7.4.0
    - qt5reactor
    - twisted
    - websocket-client

about:
  # home: [url]
  license: NASA
  # license_file: LICENSE

app:
  entry: pangalaxian
  icon: pangalacticon.ico
  summary: "Pangalaxian"

