package:
  name: pangalactic.node
  version: "4.3.dev1"

source:
  path: /home/waterbug/clones/pangalactic.node

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=4.3.dev1
    - autobahn
    - binaryornot
    - packaging
    - pynacl
    - pyqt
    - python {{PY_VER}}
    - pythonocc-core
    # pythonocc-core pulls in:
    # - freeimageplus
    # - gl2ps
    # - jpeg >=9b
    # - tbb
    - pythonqwt
    # pythonqwt pulls in
    # - numpy
    # - qtpy
    # ... and some other stuff
    - qt5reactor
    - twisted
    # twisted pulls in:
    # - service_identity
    # - zope.interface
    - websocket-client

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

