package:
  name: pangalaxian
  version: "3.2.dev10"

source:
  # path to source ... modify if necessary
  path: # C:\Users\swaterbu\clones\pangalactic.node

build:
  number: 1
  entry_points:
          - pangalaxian = pangalaxian.__main__:main

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - python {{PY_VER}}
    - menuinst
    - pangalactic.node >=3.2.dev10

about:
  # home: [url]
  license: NASA
  # license_file: LICENSE

app:
  entry: pangalaxian
  icon: pangalacticon.ico
  summary: "Pangalaxian"

