package:
  name: pangalactic.node
  version: "4.4.dev3"

source:
  path: {{path-to-source}}

build:
  entry_points:
    - pgxn = pangalactic.node.pgxn:main

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=4.4.dev3
    - autobahn
    - base58
    - binaryornot
    - ecdsa
    - packaging
    - pynacl
    - pyqt
    - python {{PY_VER}}
    - pythonocc-core
    # pythonocc-core pulls in:
    # - freeimageplus
    # - gl2ps
    # - jpeg >=9b
    # - tbb
    - pythonqwt
    # pythonqwt pulls in
    # - numpy
    # - qtpy
    # ... and some other stuff
    - qt5reactor
    - twisted
    # twisted pulls in:
    # - service_identity
    # - zope.interface
    - websocket-client

about:
  home: https://github.com/waterbug/pangalactic.node
  license: NOSA
  license_file: NOSA_18985_Pan_Galactic_Engineering_Framework_3.0.pdf

app:
  entry: pangalaxian
  icon: pangalacticon.ico
  summary: "Pangalaxian"

