package:
  name: pangalaxian
  version: "2.0"

source:
  path: # [path to source]

build:
  number: 1
  entry_points:
          - pangalaxian = pangalaxian.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menuinst
    - pangalactic.node >=2.0

about:
  # home: [url]
  license: NASA
  # license_file: LICENSE

app:
  entry: pangalaxian
  icon: pangalaxian.ico
  summary: "Pangalaxian"

