package:
  name: pangalactic
  version: "0.1.dev61"

source:
        path: /home/waterbug/gitlab/pgef

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python
    - setuptools

  run:
    - autobahn 0.17.1  # conda-forge
    - conda
    - binaryornot       # conda-forge
    - hdf5 <=1.8.18     # otherwise, get HDF5ExtError
    - inflect           # conda-forge
    - jpeg >=9b
    - matplotlib
    - numpy >=1.13.3
    - openjpeg >=2.3.0
    - pandas
    - pillow <=4.1.1    # 4.2.x is broken
    - pyqt >=5.6
    - python >=2.7
    - pytables
    - pythonocc-core    # dlr-sc
    - pytz
    - rdflib            # conda-forge
    - ruamel_yaml
    - service_identity
    - sqlalchemy
    - twisted <=16.6
    - tzlocal
    - unidecode
    - xlrd
    - xlwt
    - xlsxwriter
    - zope
    - zope.interface
    # locally created conda packages
    - louie
    - qt5reactor

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

