package:
  name: pangalactic.node
  version: "1.1.0"

source:
        path: /home/waterbug/gitlab/pangalactic.node

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python
    - setuptools

  run:
    - pangalactic.core >=1.1.0
    - autobahn
    - binaryornot
    - inflect
    - pyqt >=5.6
    - python >=2.7
    - pythonocc-core
    - pytz
    - ruamel_yaml
    - service_identity
    - sqlalchemy
    - twisted
    - zope.interface
    # locally created conda packages
    - louie
    - qt5reactor

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

