package:
  name: pangalactic.node
  version: "4.0.dev0"

source:
  path: /home/waterbug/gitlab/pangalactic.node

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=4.0.dev0
    - autobahn
    - binaryornot
    - packaging
    - pynacl
    - pyqt
    - python {{PY_VER}}
    - pythonocc-core
    - qt5reactor
    - twisted
    - websocket-client

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

