package:
  name: pangalactic.node
  version: "3.2"

source:
        path: /home/waterbug/gitlab/pangalactic.node

build:
  entry_points:
    - pangalaxian = pangalactic.node.pangalaxian:run

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - pangalactic.core >=3.2
    - autobahn
    - binaryornot
    - inflect
    - pynacl
    - pyqt
    - python {{PY_VER}}
    - pythonocc-core
    - pytz
    - qt5reactor
    - sqlalchemy
    - twisted
    - websocket-client

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

