# -*- coding: utf-8 -*-
"""
Tests for the 42 IPC protocol layer (`pangalactic.node.ipc42`).

The fixture `data/42_ipc_message.txt` is a **real message captured off the
wire** from 42 build `42-2026.07.24`, configured TX/CLIENT with its shipped
default prefixes (`SC`, `Orb`, `World`), not a hand-written approximation.
That matters: the format is generated by `sprintf` in
`Source/AutoCode/TxRxIPC.c`, so a transcription error would be invisible in a
test written from the C source.

No sockets are opened here except in the framing tests, which use a pair of
connected sockets on localhost rather than a real 42.
"""
import os
import socket
import threading

import pytest

from pangalactic.node.ipc42 import (ACK, ENDMSG, Listener42, Message42,
                                    Time42, build_message, format_value,
                                    parse_message, parse_value)

HERE = os.path.dirname(os.path.abspath(__file__))
CAPTURE = os.path.join(HERE, 'data', '42_ipc_message.txt')


@pytest.fixture(scope='module')
def captured():
    with open(CAPTURE) as f:
        return f.read()


# ---------------------------------------------------------------- parsing

def test_01_parses_a_real_captured_message(captured):
    """CASE: the real wire format parses with nothing left over

    `unparsed` is the important assertion.  Anything the parser does not
    recognise is collected rather than dropped, so a format change upstream
    shows up as data instead of as silence -- and right now there should be
    none at all.
    """
    msg = parse_message(captured)
    assert msg.time is not None
    assert msg.unparsed == [], f'unrecognised lines: {msg.unparsed[:5]}'
    assert len(msg.values) == 176


def test_02_time_line(captured):
    """CASE: the TIME line, which 42 writes as year-doy-hh:mm:ss"""
    msg = parse_message(captured)
    assert msg.time == Time42(2024, 99, 0, 0, 0.1)
    assert msg.time.seconds_of_day == pytest.approx(0.1)


def test_03_vector_and_scalar_values(captured):
    """CASE: bracketed vectors become float lists; bare numbers stay scalar"""
    msg = parse_message(captured)
    qn = msg.values['SC[0].qn']
    assert isinstance(qn, list) and len(qn) == 4
    assert qn[0] == pytest.approx(0.2970455206341)
    wn = msg.values['SC[0].wn']
    assert isinstance(wn, list) and len(wn) == 3


def test_04_prefix_filtering_matches_42_semantics(captured):
    """CASE: prefix matching is a literal string prefix, as 42 does it

    42 filters with strncmp(line, Prefix, strlen(Prefix)), so "SC" matches
    every SC[...] line and a narrower prefix selects a subset.  Keeping the
    same semantics means a caller can filter exactly how it configures.
    """
    msg = parse_message(captured)
    assert len(msg.names_with_prefix('SC')) == 9
    assert len(msg.names_with_prefix('Orb')) == 2
    assert len(msg.names_with_prefix('World')) == 165
    assert msg.names_with_prefix('SC[0].AC') == []
    assert len(msg.names_with_prefix('SC[0].q')) == 1


@pytest.mark.parametrize('text,expected', [
    ('[1.0e+00 2.0e+00]', [1.0, 2.0]),
    ('[]', []),
    ('0', 0),
    ('-3', -3),
    ('1.5e-03', 0.0015),
    ('not a number', 'not a number'),
])
def test_05_parse_value_forms(text, expected):
    """CASE: the value grammar, including the unparseable fallback"""
    assert parse_value(text) == expected


def test_06_endmsg_is_not_a_value(captured):
    """CASE: the terminator is framing, not data"""
    msg = parse_message(captured)
    assert ENDMSG not in msg.values
    assert not any(ENDMSG in n for n in msg.values)


# ---------------------------------------------------------------- building

def test_07_build_message_round_trips():
    """CASE: what we send to 42 parses back to what we meant"""
    t = Time42(2026, 205, 12, 34, 56.789)
    values = {'SC[0].qn': [0.0, 0.0, 0.0, 1.0], 'SC[0].wn': [1e-3, 0.0, 0.0]}
    text = build_message(t, values)
    assert text.endswith(ENDMSG + '\n')
    back = parse_message(text)
    assert back.time == t
    assert back.values['SC[0].qn'] == pytest.approx([0.0, 0.0, 0.0, 1.0])
    assert back.values['SC[0].wn'] == pytest.approx([1e-3, 0.0, 0.0])


def test_08_format_value_matches_42s_own_notation(captured):
    """CASE: our formatter produces what 42's sprintf produces

    42 writes "%18.12le", so a value we send should be re-readable by the
    same parser that reads 42's output -- checked here by round-tripping a
    value taken *from* the capture.
    """
    msg = parse_message(captured)
    original = msg.values['SC[0].qn']
    rendered = format_value(original)
    assert parse_value(rendered) == pytest.approx(original)


# ---------------------------------------------------------------- framing

def _socketpair():
    """A connected pair, standing in for 42 and us."""
    lis = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    lis.bind(('127.0.0.1', 0))
    lis.listen(1)
    port = lis.getsockname()[1]
    holder = {}

    def _connect():
        holder['client'] = socket.create_connection(('127.0.0.1', port))

    t = threading.Thread(target=_connect)
    t.start()
    server_side, _ = lis.accept()
    t.join()
    lis.close()
    return holder['client'], server_side


def test_09_read_message_reassembles_a_split_send(captured):
    """CASE: one message arriving in several TCP segments

    42 sends one message per simulation step, but nothing guarantees it
    arrives in one read.  (42's *own* RX side does assume that -- a
    constraint on what we send, not on what we can receive.)
    """
    sender, receiver = _socketpair()
    lis = Listener42()
    lis.conn = receiver
    try:
        payload = captured.encode()
        mid = len(payload) // 2
        threading.Thread(target=lambda: (sender.sendall(payload[:mid]),
                                         sender.sendall(payload[mid:]))).start()
        text = lis.read_message()
        assert text is not None
        msg = parse_message(text)
        assert len(msg.values) == 176
        assert msg.unparsed == []
    finally:
        sender.close()
        receiver.close()


def test_10_read_message_splits_coalesced_messages(captured):
    """CASE: two messages arriving in one read are not merged"""
    sender, receiver = _socketpair()
    lis = Listener42()
    lis.conn = receiver
    try:
        threading.Thread(
            target=lambda: sender.sendall((captured + captured).encode())
        ).start()
        first = lis.read_message()
        second = lis.read_message()
        for text in (first, second):
            assert text is not None
            assert len(parse_message(text).values) == 176
    finally:
        sender.close()
        receiver.close()


def test_11_read_message_returns_none_on_close():
    """CASE: 42 exiting closes the connection cleanly"""
    sender, receiver = _socketpair()
    lis = Listener42()
    lis.conn = receiver
    try:
        sender.close()
        assert lis.read_message() is None
    finally:
        receiver.close()


def test_12_ack_is_exactly_four_bytes():
    """CASE: the acknowledgement 42 blocks on

    42 does read(Socket, Ack, 4) after every TX and does not inspect the
    content.  The length is the contract: fewer bytes and the simulation
    stalls forever.
    """
    assert len(ACK) == 4


def test_13_messages_acks_after_yielding(captured):
    """CASE: the ack follows the yield, so a slow consumer paces 42

    This ordering is the whole reason run/pause/step needs no change to 42:
    a consumer that stops iterating stops the simulation.
    """
    sender, receiver = _socketpair()
    lis = Listener42()
    lis.conn = receiver
    try:
        threading.Thread(target=lambda: sender.sendall(captured.encode())).start()
        gen = lis.messages()
        msg = next(gen)
        assert len(msg.values) == 176
        # the ack has not been sent yet -- 42 would still be blocked here
        sender.settimeout(0.3)
        with pytest.raises((socket.timeout, TimeoutError)):
            sender.recv(4)
        # advancing the generator sends it
        threading.Thread(target=lambda: sender.sendall(captured.encode())).start()
        next(gen)
        sender.settimeout(2.0)
        assert sender.recv(4) == ACK
    finally:
        sender.close()
        receiver.close()
